### ISSUE TITLE
[오류 제보] HTML 첨부

### ISSUE THREAD

**Issue by da-nyee** [PapimonLikelion/web-hosting-mockup#1]
## 문제 상황
선택했던 파일을 취소하고, 곧바로 다시 해당 파일을 선택했을 때 제대로 선택되지 않는 문제가 있습니다!

### 정상 화면
https://user-images.githubusercontent.com/50176238/132326153-0b5efa64-25a4-41a4-8443-6cc20f09ce61.mov

### 오류 화면
https://user-images.githubusercontent.com/50176238/132326068-051ff180-a2f0-4782-abfc-5d2afc2304ef.mov

**Comment by joelonsw** [comment]
https://github.com/PapimonLikelion/web-hosting/commit/4cbafa0fdab102b2b8a830c3066a9e6cec813bad

해당 커밋으로 문제 해결하였습니다~
오류 제보 감사드립니다!! 🙌🙌🙌🙌🙌
