### ISSUE TITLE
[건의] min width 설정이 필요해보입니다.

### ISSUE THREAD

**Issue by unluckyjung** [PapimonLikelion/web-hosting-mockup#2]
## width 1279
![image](https://user-images.githubusercontent.com/43930419/144720645-d44cd169-e8e3-4ea8-808b-c8b82b4c8609.png)

## width 1270

![image](https://user-images.githubusercontent.com/43930419/144720802-736730b6-a5ac-4580-9623-573c0c642280.png)
- 일정 이하의 width가 된다면,  **배포된 페이지 보기** 가 노출되지 않는 문제가 발생합니다. **(hegiht 는 문제가 없습니다.)**
  - 미디어 쿼리를 이용하여, width크기를 보고 페이지를 더 키워달라는 메시지를 띄우는 작업이 있으면 좋겠습니다.

**Comment by joelonsw** [comment]
먼저 프로젝트에 관심 가져 주셔서 감사합니다 :) 
배포된 페이지 보기 기능은 PC 환경에서만 지원하고자 하였습니다. 
모바일 및 태블릿 환경에서 사용할 때에는 메인 기능인 배포가 배포된 페이지 보기 기능에 가려지면 안 된다고 생각했기 때문이에요. 
따라서 현재로써는 ipad pro의 width 픽셀 사이즈인 1024 px 이하에서는 "배포된 페이지 보기" 기능을 보여주지 않고 있습니다. 

포츈과 얘기를 나눠보기 태블릿 사이즈 정도에서는 배포된 페이지 보기 기능을 보여줘도 될 것 같기도 하네요! 🤔🤔

**Comment by unluckyjung** [comment]
pc에서도, 일정 width이하인경우, 배포된 페이지 보기 기능만 숨기는것이 아니라 전체 페이지를 **페이지를 키워주세요** 라는 문구를 가진 화면으로 바꾸는건 어떨까요?

피씨 사용자 입장에서도 배포된 페이지보기 기능이 있는지를 모를 가능성이 종종 있을꺼 같습니다.

**Comment by joelonsw** [comment]
페이지보기 기능이 메인 기능을 해치지는 않았으면 하는 바램이라서 "페이지를 키워주세요" 문구 자체는 띄워주고 싶지 않네요!
대신 PC 사용자 입장에서도 기능을 발견할 수 없겠다라는 이슈는 저도 공감합니다!
해당 페이지보기 기능을 안 보이게 하는 건 width가 750px 이하로 떨어졌을 때 (일반 ipad width가 768px) 로 수정해보는 것 어떨까요??

**Comment by unluckyjung** [comment]
이부분은 조금 기획쪽인 부분이니, 영상님이 보셨을때 괜찮으신 방향으로 선택하시면 되겠습니다 ㅎㅎ
이슈는 클로즈할게요.

**Comment by joelonsw** [comment]
좋은 건의 감사드립니다 포츈!!!
컨트리뷰터에 이름 뚝딱 올려드릴게요 :) :)
앞으로도 많은 관심 부탁드립니다 🚀🚀
